#!/usr/bin/env python3
"""Build Bhosari MIDC welding-electrode prospect CSVs from curated public sources."""

from __future__ import annotations

import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
TODAY = "2026-09-03"

# company: name, aka, address, block, industry, size, phone, phone_alt, email, website,
# contact, role, conf, gstin, cin, directors, year, employees, processes, electrodes,
# volume, supplier, pitch, source, notes, parked_reason (if parked)
RAW: list[dict] = []


def add(**kwargs):
    RAW.append(kwargs)


# --- Tier 1: researched / directory-enriched ---
add(
    name="SNEHA Industries",
    aka="Sneha Industries",
    address="J-40, S Block, MIDC Bhosari, Pune - 411026",
    block="S Block / J-40",
    industry="Heavy fabrication",
    size="SME",
    phone="+91 98236 32332",
    phone_alt="",
    email="info@snehaindustries.com",
    website="https://snehaindustries.com",
    contact="Swapnil Sawant",
    role="Director",
    conf="High",
    year="1993",
    employees="",
    processes="SMAW;GTAW;GMAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="VMC/CNC + heavy & sheet fab — E7018/E6013 + SS E308L",
    source="Website",
    notes="Plant: J-40 S Block; VMC/CNC machining, TIG welding, sheet metal & heavy fabrication",
    products="VMC & CNC machining; sheet-metal components; heavy fabrication; TIG welding; fluid-handling parts",
    plant="J-40, S Block plant",
)
add(
    name="Jaisons Engineers & Consultants",
    aka="Jaisons Engineers",
    address="Plot No. 48, T Block, Near Rose Garden, Gawali Matha, MIDC Bhosari, Pune - 411026",
    block="T Block",
    industry="Heavy fabrication",
    size="SME",
    phone="+91 99701 99457",
    phone_alt="+91 84591 18862",
    email="jaisonsengineers20@gmail.com",
    website="https://www.jaisonsglobal.com",
    contact="Sajid Shaikh",
    role="Purchase",
    conf="Med",
    year="2020",
    employees="",
    processes="SMAW;GMAW;GTAW;Cutting",
    electrodes="E7018;E6013;E308L;Cutting",
    volume="High",
    pitch="Heavy fab + PEB + boiler works — Bharatweld E7018 + cutting rods",
    source="Website",
    notes="Also sales@jaisonsglobal.com; CNC/laser/plasma cutting, PEB, welding & painting",
    products="Heavy fabrication; PEB structures; boiler manufacturing; CNC/laser/plasma cutting; welding & painting",
    plant="T-48 Gawali Matha plant",
)
add(
    name="MILKON Heavy Engineering Pvt Ltd",
    aka="Milkon Heavy Engineering Co.",
    address="T-Block, Plot No. 103 / S-8, MIDC Bhosari, Pune - 411026",
    block="T Block",
    industry="Boiler/tank manufacturers",
    size="Large",
    phone="+91 98600 87875",
    phone_alt="+91 20 66301555",
    email="info@milkonengineers.com",
    website="https://www.milkondairyequipment.com",
    contact="",
    role="Purchase",
    conf="Med",
    year="1983",
    employees="",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="SS dairy tanks/silos & process equipment — E308L + E7018 coded welds",
    source="Website",
    notes="Works: Bhosari T-103; also sales@milkonengineers.com; +91 78754 44955 / 81498 06559",
    products="Dairy process equipment; milk silos & storage tanks; ghee boilers; bulk milk coolers; SS pumps & blenders",
    plant="T-103 Bhosari works",
)
add(
    name="Sankalp Steeltech Corporation Pvt Ltd",
    aka="Sankalp Steeltech",
    address="Plot No. 140/141, Sector No. 7, PCNTDA, Bhosari, Pune - 411026",
    block="Sector 7",
    industry="Steel fabrication",
    size="SME",
    phone="+91 73500 04114",
    phone_alt="+91 20 66113892",
    email="info@sankalpsteeltech.com",
    website="https://www.sankalpsteeltech.com",
    contact="",
    role="Purchase",
    conf="Med",
    year="1993",
    employees="",
    processes="SMAW;GMAW;Cutting",
    electrodes="E6013;E7018;Cutting",
    volume="High",
    pitch="Steel stockist + fab support — E6013/E7018 for in-house & customer fab",
    source="Website",
    notes="Also +91 87999 27473; mild steel beams, plates, pipes; laser cutting / hardening services",
    products="Mild steel stockist (beams, plates, pipes); laser cutting; hardening; metal fabrication support",
    plant="Sector 7 Plot 140/141",
)
add(
    name="MACHINESPACE India Pvt Ltd",
    aka="Machine Space",
    address="Plot No. 76, Sector No. 7, PCNTDA, MIDC Bhosari, Pune - 411026",
    block="Sector 7",
    industry="Sheet-metal fabrication",
    size="SME",
    phone="+91 95958 58695",
    phone_alt="",
    email="info@machinespace.in",
    website="https://www.machinespace.in",
    contact="Sadik Mujavar",
    role="Director",
    conf="High",
    year="2020",
    employees="",
    processes="GTAW;GMAW;SMAW",
    electrodes="E6013;E7018;E308L",
    volume="High",
    pitch="Certified TIG/MIG Al & SS welding — E308L + Al specialty; MS E6013/E7018",
    source="Website",
    notes="Enclosures, cabinets, defence/aerospace components; WPS/PQR certified welding",
    products="TIG/MIG welding (Al & SS); custom enclosures & cabinets; CNC/VMC precision parts; structural fabrication",
    plant="Sector 7 Plot 76",
)
add(
    name="Silson Boilers",
    aka="Silson Group",
    address="115/2, General Block, MIDC, Bhosari, Pune - 411026",
    block="General Block",
    industry="Boiler/tank manufacturers",
    size="Large",
    phone="+91 94050 34183",
    phone_alt="+91 98220 53375",
    email="response@silsonboilers.in",
    website="https://www.silsonboilers.in",
    contact="",
    role="Purchase",
    conf="Med",
    year="1989",
    employees="110+",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="IBR boiler fab — lead with Bharatweld E7018; SS parts need E308L",
    source="Website;Maps",
    notes="20,000+ sq ft Bhosari facility; ISO 9001 & IBR",
)
add(
    name="Rakhoh Industries Pvt Ltd",
    aka="Rakhoh Boilers",
    address="S-11, T Block, MIDC Industrial Area, Bhosari, Pune - 411026",
    block="T Block",
    industry="Boiler/tank manufacturers",
    size="Large",
    phone="+91 20 66308333",
    phone_alt="+91 20 66308340",
    email="enquiry@rakhoh.com",
    website="https://www.rakhoh.com",
    contact="",
    role="Purchase",
    conf="Med",
    year="1983",
    employees="500+",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="Large boiler OEM — E7018 volume + maintenance cutting electrodes",
    source="Website",
    notes="Established steam boiler manufacturer in T Block",
)
add(
    name="Shubham Udyog",
    aka="",
    address="359 MIDC, Bhosari, Pimpri-Chinchwad, Pune - 411026",
    block="MIDC Bhosari",
    industry="Boiler/tank manufacturers",
    size="SME",
    phone="+91 80480 46755",
    phone_alt="",
    email="shubhamudyog@yahoo.co.in",
    website="https://www.shubhamudyogpune.in",
    contact="",
    role="Owner",
    conf="Med",
    year="1989",
    employees="",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="IBR boilers & pressure parts — Bharatweld E7018 trial pack",
    source="Website",
    notes="Boilers, thermic fluid heaters, heat exchangers, SS fabrication",
)
add(
    name="Fabri-Tek Engineers",
    aka="Fabritek",
    address="S-151, M.I.D.C. Bhosari, Pune - 411026",
    block="S Block",
    industry="Boiler/tank manufacturers",
    size="Large",
    phone="+91 83088 15577",
    phone_alt="+91 98814 98707",
    email="info@fabritekengineers.com",
    website="https://fabritekengineers.com",
    contact="Mr. Baba Kolase / Mr. Kunal Raut",
    role="Owner",
    conf="High",
    year="",
    employees="",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="ASME pressure vessels & tanks — E7018 + E308L coded welding",
    source="Website",
    notes="Directors listed on contact page; also Unit-II Chakan",
)
add(
    name="Pilon Engineering",
    aka="",
    address="Plot No. 513/2/1, J Block, MIDC, Bhosari, Pune - 411026",
    block="J Block",
    industry="Boiler/tank manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="sales@pilonengineering.com",
    website="https://pilonengineering.com",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="Coded pressure vessels — Bharatweld E7018 for CS shells",
    source="Website",
    notes="info@pilonengineering.com also listed",
)
add(
    name="Sterling Engineers & Boilers Pvt Ltd",
    aka="Sterling Engineers",
    address="T-71/1-A/7, General Block, MIDC, Bhosari, Pune - 411026",
    block="General Block / T Block",
    industry="Boiler/tank manufacturers",
    size="SME",
    phone="+91 96890 11211",
    phone_alt="",
    email="sterlingboiler@gmail.com",
    website="https://www.sterlingengineers.in",
    contact="",
    role="Purchase",
    conf="Med",
    year="2012",
    employees="",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013",
    volume="High",
    pitch="Pressure vessels, chimneys, tanks — E7018 structural & pressure welds",
    source="Website",
    notes="",
)
add(
    name="Advance Preci-Tech",
    aka="",
    address="J Block, Plot No. 166, MIDC, Bhosari, Pune - 411026",
    block="J Block",
    industry="Heavy fabrication",
    size="SME",
    phone="+91 97669 15151",
    phone_alt="",
    email="enquiry@advanceprecitech.com",
    website="https://advanceprecitech.com",
    contact="",
    role="Purchase",
    conf="Med",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="Heavy pressure vessel fab (up to 200T) — high E7018 demand",
    source="Website",
    notes="",
)
add(
    name="Radiant Heat Exchanger Pvt Ltd",
    aka="Radiant Engineers",
    address="S-116/2, MIDC, Bhosari, Pune - 411026",
    block="S Block",
    industry="Heavy engineering",
    size="Large",
    phone="+91 20 40718000",
    phone_alt="+91 20 40718026",
    email="sales@radiantengineers.com",
    website="https://www.radiantengineers.com",
    contact="",
    role="Purchase",
    conf="Med",
    year="1977",
    employees="38+",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="Heat exchangers & pressure vessels — E7018 + E308L for process equipment",
    source="Website",
    notes="Plant 2: S-19 MIDC Bhosari",
)
add(
    name="Finix Engineering Works",
    aka="",
    address="Sector No. 10, Plot No. 246, PCNTDA, MIDC, Bhosari, Pune - 411026",
    block="Sector 10",
    industry="Steel fabrication",
    size="SME",
    phone="",
    phone_alt="",
    email="sales@finixengineering.com",
    website="https://finixengineering.com",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="44+",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="SS/MS vessels & tanks — E7018 + E308L sample kit",
    source="Website",
    notes="25+ years steel fabrication",
)
add(
    name="Essem Engineers & Fabricators",
    aka="ESSEM",
    address="Sector No. 10, Plot No. 147, PCNTDA, Bhosari, Pune - 411026",
    block="Sector 10",
    industry="Sheet-metal fabrication",
    size="SME",
    phone="+91 94220 14693",
    phone_alt="+91 80875 28594",
    email="essemengineers1@gmail.com",
    website="https://essemengineersandfab.com",
    contact="Madhukar Baloji",
    role="Owner",
    conf="High",
    year="2002",
    employees="",
    processes="SMAW;GMAW;Cutting",
    electrodes="E6013;E7018;E308L;Cutting",
    volume="Med",
    pitch="Laser + SS/MS fab & MH equipment — E6013/E7018 + cutting rods",
    source="Website",
    notes="GSTIN 27AICPB4333R1Z4",
    gstin="27AICPB4333R1Z4",
)
add(
    name="Brahma Techno Engineering",
    aka="Kalpak Engineers",
    address="Plot No. BGP 111, General T Block, Bhosari MIDC, Pune - 411026",
    block="T Block",
    industry="Steel fabrication",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="https://www.indiamart.com/kalpak-engineers/",
    contact="Nitin Sawant",
    role="Purchase",
    conf="Med",
    year="2008",
    employees="",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="Boilers, tanks, heat exchangers, SS fab — E7018 primary",
    source="IndiaMART",
    notes="Also listed as Kalpak Engineers on IndiaMART",
)
add(
    name="Diamond Fabrication I Pvt Ltd",
    aka="Diamond Fabrications India",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Heavy fabrication",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="https://www.indiamart.com/diamond-fabrications-india/",
    contact="Aseem S. Kogekar",
    role="Owner",
    conf="Med",
    year="",
    employees="",
    directors="Subhash Anant Kogekar; Aseem S. Kogekar",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="Process equipment & pressure vessels — coded E7018/E308L",
    source="IndiaMART",
    notes="CEO Aseem S. Kogekar; MS/SS/exotic fab",
)
add(
    name="BMC Enterprises",
    aka="",
    address="Plot No. J-399, MIDC, Bhosari, Pune - 411026",
    block="J Block",
    industry="Heavy engineering",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="https://www.indiamart.com/bmcent-com-990956/",
    contact="Babulal Mohiddin Choudhari",
    role="Owner",
    conf="Med",
    year="1993",
    employees="11-25",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013;E308L",
    volume="Med",
    pitch="Heavy CNC + fabrication of vessels — E7018 for pressure parts",
    source="IndiaMART",
    notes="Proprietor Abbas / Babulal Choudhari; 6 bays, overhead cranes",
)
add(
    name="Fabtech Projects & Engineers Ltd",
    aka="Fabtech",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Heavy fabrication",
    size="Large",
    phone="",
    phone_alt="",
    email="",
    website="https://www.indiamart.com/fabtech-projects-engineers-limited/",
    contact="D Thorat",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="EPC process equipment — high E7018/E308L electrode consumption",
    source="IndiaMART",
    notes="Pressure vessels, columns, heat exchangers; large turnover band",
)
add(
    name="Datsons Engineering Works Pvt Ltd",
    aka="Datsons",
    address="Plot No. W-13, 14, 15, S Block, MIDC, Bhosari, Pune - 411026",
    block="S Block / W",
    industry="Sheet-metal fabrication",
    size="Large",
    phone="+91 20 27127414",
    phone_alt="+91 90110 97737",
    email="",
    website="https://www.datsonsengg.com",
    contact="",
    role="Purchase",
    conf="Med",
    year="1983",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E6013;E7018",
    volume="High",
    pitch="Auto sheet-metal & canopies — E6013 volume + E7018 structural",
    source="Website",
    notes="Unit 1 Bhosari; Unit 2 Chakan; +91 20 27120909 also listed",
)
add(
    name="Ganesh Engineering Works",
    aka="",
    address="S-188 MIDC Bhosari, Near Color Bond company, Pune - 411026",
    block="S Block",
    industry="Sheet-metal fabrication",
    size="SME",
    phone="+91 98900 81081",
    phone_alt="+91 20 27120876",
    email="sushant@ganeshengg.co.in",
    website="http://www.sme.in/ganeshengineering/",
    contact="Mr. Sushant Shah",
    role="Owner",
    conf="High",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E6013;E7018",
    volume="Med",
    pitch="Auto sheet & fabricated components — Bharatweld E6013 cartons",
    source="Website",
    notes="Supplies Tata Motors, Force Motors, etc.",
)
add(
    name="SP Engineers",
    aka="",
    address="142, MIDC Industrial Area, Bhosari, PCMC - 411026",
    block="MIDC Bhosari",
    industry="Steel fabrication",
    size="Micro",
    phone="+91 20 27125972",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Owner",
    conf="Low",
    year="",
    employees="",
    processes="SMAW",
    electrodes="E6013;E7018",
    volume="Med",
    pitch="Steel/door/gate fab — start with E6013 sample",
    source="AskLaila;Directory",
    notes="Near Ankit Traders",
)
add(
    name="K Engineering & Fab Works",
    aka="",
    address="Plot No. 235, Sector-10, PCNTDA, Bhosari, Pune - 411026",
    block="Sector 10",
    industry="Structural fabrication",
    size="Micro",
    phone="",
    phone_alt="",
    email="",
    website="https://www.tradeindia.com/",
    contact="Mr. Dinesh Bhagwat Choudhary",
    role="Owner",
    conf="Med",
    year="2013",
    employees="",
    processes="SMAW",
    electrodes="E6013;E7018",
    volume="Med",
    pitch="Industrial & gate fabrication — E6013 primary",
    source="TradeIndia",
    notes="Gate, grill, industrial fab services",
)
add(
    name="Pressure Vessels (India)",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Boiler/tank manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="Vessel manufacturer — verify plot & phone on Maps then pitch E7018",
    source="Chamber directory (GCCIA)",
    notes="Name from Bhosari MIDC chamber list; re-verify before call",
)
add(
    name="Ultra Engineers",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Heavy engineering",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013",
    volume="Med",
    pitch="Engineering OEM — E7018 for equipment frames",
    source="Chamber directory (GCCIA)",
    notes="Re-verify address/phone on Google Maps",
)
add(
    name="Gas Processing Equipment Pvt Ltd",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Heavy engineering",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GTAW",
    electrodes="E7018;E6013;E308L",
    volume="High",
    pitch="Process equipment fab — E7018 + stainless electrodes",
    source="Chamber directory (GCCIA)",
    notes="Re-verify on Maps/GST",
)
add(
    name="Teknik Plant And Machinery Mfg Co Pvt Ltd",
    aka="Teknik",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Machine/equipment manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013",
    volume="Med",
    pitch="Plant & machinery OEM — E7018 baseframe welding",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="Yash Systems Manufacturing Co Pvt Ltd",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Machine/equipment manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013",
    volume="Med",
    pitch="Systems manufacturing — electrode trial for fab shop",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="Power Formers Engineers Pvt Ltd",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Heavy engineering",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013",
    volume="Med",
    pitch="Engineering fab — Bharatweld E6013/E7018 intro pack",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="Dairy Tech India",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Machine/equipment manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GTAW",
    electrodes="E6013;E308L;E7018",
    volume="Med",
    pitch="Dairy equipment SS fab — E308L + E6013",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="Accusharp Cutting Tools Pvt Ltd",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Machine/equipment manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW",
    electrodes="E6013;E7018",
    volume="Low",
    pitch="Tooling OEM — maintenance welding electrodes",
    source="Chamber directory (GCCIA)",
    notes="Lower SMAW volume; maintenance angle",
)
add(
    name="National Engineering Company",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Heavy engineering",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013",
    volume="Med",
    pitch="Engineering company — verify fab intensity then pitch E7018",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="Patange Industries Pvt Ltd",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Heavy fabrication",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E6013;E7018",
    volume="Med",
    pitch="Industrial manufacturer — Maps verify then E6013/E7018 visit",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="Sydler Group",
    aka="Sydler Group of Companies",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Heavy engineering",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013",
    volume="Med",
    pitch="Group manufacturing unit — electrode supply discussion",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="H C & Company",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="General engineering",
    size="Micro",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Owner",
    conf="Low",
    year="",
    employees="",
    processes="SMAW",
    electrodes="E6013",
    volume="Low",
    pitch="Engineering unit — E6013 small-pack entry",
    source="Chamber directory (GCCIA)",
    notes="Tier may adjust after Maps classification",
)
add(
    name="Konzert Toolings",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Machine/equipment manufacturers",
    size="Micro",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW",
    electrodes="E6013;E7018",
    volume="Low",
    pitch="Tooling shop — fixture & repair welding electrodes",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="Spaco Technologies",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Machine/equipment manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E6013;E7018",
    volume="Low",
    pitch="Tech/equipment maker — maintenance electrode kit",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="Subhash Engineering Pvt Ltd",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Heavy engineering",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013",
    volume="Med",
    pitch="Engineering fab — Bharatweld E7018 intro",
    source="Chamber directory (GCCIA)",
    notes="Listed as Subhash Pvt Ltd on chamber list",
)
add(
    name="Pune Metagraph",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Machine/equipment manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW",
    electrodes="E6013;E7018",
    volume="Low",
    pitch="Verify metalwork intensity; maintenance electrodes if fab present",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="Protocontrol Instruments (I) Pvt Ltd",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Machine/equipment manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW",
    electrodes="E6013",
    volume="Low",
    pitch="Instrument OEM — low volume; maintenance only",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="Elscint Automation",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Machine/equipment manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E6013;E7018",
    volume="Med",
    pitch="Automation equipment frames — E6013/E7018 for fab",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="Symtronics Automation Pvt Ltd",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Machine/equipment manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E6013;E7018",
    volume="Med",
    pitch="Automation OEM — baseframe welding consumables",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="General Industrial Controls Pvt Ltd",
    aka="GIC",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Machine/equipment manufacturers",
    size="Large",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E6013;E7018",
    volume="Med",
    pitch="Controls OEM — plant maintenance + fab electrodes",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="KTR Couplings India Pvt Ltd",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Machine/equipment manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW",
    electrodes="E6013;E7018",
    volume="Low",
    pitch="Couplings OEM — maintenance welding only",
    source="Chamber directory (GCCIA)",
    notes="",
)
add(
    name="Frontline Electronics Ltd",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Industrial maintenance",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;Cutting",
    electrodes="E6013;Cutting",
    volume="Low",
    pitch="Plant maintenance angle if metal shop present",
    source="Chamber directory (GCCIA)",
    notes="May be light fab; verify before heavy pitch",
)
add(
    name="Maple Biotech Pvt Ltd",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Industrial maintenance",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;Cutting",
    electrodes="E6013;E308L;Cutting",
    volume="Low",
    pitch="Biotech plant maintenance — SS electrodes + cutting",
    source="Chamber directory (GCCIA)",
    notes="Maintenance welding angle",
)
add(
    name="Dynamic Engineering And Solutions",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Material-handling equipment",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="https://www.indiamart.com/dynnamic-engineering/",
    contact="P M Kulkarni",
    role="Owner",
    conf="Med",
    year="2005",
    employees="26-50",
    gstin="27AAMFD4893N1ZL",
    processes="SMAW;GMAW",
    electrodes="E6013;E7018",
    volume="Med",
    pitch="Conveyors & process equipment — steady E6013/E7018",
    source="IndiaMART",
    notes="GST 27AAMFD4893N1ZL; CEO Pradeep Madhukar Kulkarni",
)
add(
    name="Malgudi Cranes & Components",
    aka="Malgudi",
    address="Plot No. 238, Sector No. 7, Bhosari MIDC, Pune - 411026",
    block="Sector 7",
    industry="Crane manufacturers",
    size="SME",
    phone="+91 94225 12489",
    phone_alt="+91 97666 25828",
    email="sales@malgudicranes.com",
    website="https://malgudicranes.com",
    contact="Mallesh B. K.",
    role="Owner",
    conf="High",
    year="2000",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013",
    volume="High",
    pitch="EOT/goliath crane girders — Bharatweld E7018 for structural welds",
    source="Website",
    notes="2000+ crane installations claimed",
)
add(
    name="Malgudi Associates",
    aka="",
    address="Plot No. 149/2, PCNTDA, Sector No. 7, MIDC, Bhosari, Pune - 411026",
    block="Sector 7",
    industry="Crane manufacturers",
    size="SME",
    phone="+91 79711 90892",
    phone_alt="",
    email="",
    website="https://www.malgudiassociates.com",
    contact="Mallesh B. K. / Ravikumar Mallappa Kummur",
    role="Owner",
    conf="High",
    year="2009",
    employees="11-25",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013",
    volume="High",
    pitch="EOT & jib cranes — E7018 girder welding opportunity",
    source="Website;IndiaMART",
    notes="Clients include JCB, Bharat Forge, John Deere",
)
add(
    name="Super Crane Industries",
    aka="",
    address="Unit 2, J Block, EL-59, MIDC Bhosari, Pune - 411026",
    block="J Block",
    industry="Crane manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="https://www.super-crane.com",
    contact="Mr. John Daniel / Mrs. Mercy John",
    role="Owner",
    conf="High",
    year="1998",
    employees="11-25",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013",
    volume="High",
    pitch="EOT/HOT cranes & hoists — E7018 structural fab",
    source="Website",
    notes="Promoter Mercy John; clients Thermax, Bharat Bijlee",
)
add(
    name="Shalini Cranes & Equipments Pvt Ltd",
    aka="Shalin Material Handling",
    address="S-99, MIDC, Bhosari, Pune - 411026",
    block="S Block",
    industry="Crane manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="https://www.exportersindia.com/shalini-cranes-equipments-pvt-ltd/",
    contact="",
    role="Purchase",
    conf="Low",
    year="1997",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013",
    volume="High",
    pitch="Jib/EOT/hydraulic cranes — E7018 for load-bearing welds",
    source="ExportersIndia",
    notes="",
)
add(
    name="Gulmohar Engineering Works",
    aka="GEW Cranes",
    address="Plot No. 299, Sector No. 7, PCNTDA, Bhosari, Near Gold Star Weigh Bridge, Pune - 411026",
    block="Sector 7",
    industry="Crane manufacturers",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="https://www.gewcranes.co.in",
    contact="Mr. Sandeep Dalal",
    role="Owner",
    conf="High",
    year="2009",
    employees="26-50",
    processes="SMAW;GMAW",
    electrodes="E7018;E6013",
    volume="High",
    pitch="EOT cranes & hoists — Bharatweld E7018 for crane fab",
    source="Website",
    notes="Also Alandi unit listed on profile",
)
add(
    name="CARMAC Technologies Pvt Ltd",
    aka="",
    address="J-65/1, J Block MIDC, Bhosari, Pune - 411026",
    block="J Block",
    industry="Trailer/body builders",
    size="SME",
    phone="",
    phone_alt="",
    email="",
    website="https://www.exportersindia.com/carmac-technologies-pvt-ltd/",
    contact="Ritesh Srinivasan",
    role="Owner",
    conf="High",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E6013;E7018",
    volume="High",
    pitch="Trailers & chassis — high E6013/E7018 body-builder volume",
    source="ExportersIndia",
    notes="Modular/boat/cable drum trailers; welding rotator products",
)
add(
    name="Natraj Enterprises",
    aka="",
    address="W-176, S Block, MIDC, Bhosari, Pune - 411026",
    block="S Block / W",
    industry="Material-handling equipment",
    size="SME",
    phone="+91 20 46764446",
    phone_alt="",
    email="",
    website="https://www.exportersindia.com/natraj-enterprises-pune/",
    contact="Dheeraj Desai",
    role="Owner",
    conf="High",
    year="1980",
    employees="20-50",
    processes="SMAW;GMAW",
    electrodes="E6013;E7018",
    volume="Med",
    pitch="MH equipment & trailers — E6013/E7018 for structures",
    source="ExportersIndia",
    notes="Trolleys, stackers, floor cranes, heavy-duty trailers",
)
add(
    name="Sandeep Engineering Works",
    aka="",
    address="Plot No. 169, Sector-10, PCNTDA, Bhosari, Pune - 411026",
    block="Sector 10",
    industry="Foundries",
    size="SME",
    phone="+91 95525 95391",
    phone_alt="+91 98220 36430",
    email="info@sewpune.com",
    website="http://www.sme.in/sandeepengineering/",
    contact="Mr. D S Jagtap",
    role="Owner",
    conf="High",
    year="",
    employees="",
    processes="SMAW;Hardfacing;Cutting",
    electrodes="E6013;Mn hardfacing;Cutting",
    volume="Low",
    pitch="Die casting foundry — Mn hardfacing + repair electrodes",
    source="Website",
    notes="Aluminium die/sand casting; Sandeepengg.work@gmail.com",
)
add(
    name="S.S. Engineering Works",
    aka="SS Engineering Works",
    address="Plot No. 271, Sector No. 07, PCNTDA, Bhosari, Pune - 411026",
    block="Sector 7",
    industry="Machine shops",
    size="SME",
    phone="+91 20 66303495",
    phone_alt="+91 98228 98241",
    email="",
    website="https://sseworks.in",
    contact="Sanjay Satav",
    role="Owner",
    conf="High",
    year="",
    employees="",
    processes="SMAW",
    electrodes="E6013;E7018",
    volume="Low",
    pitch="Machine components + fabrication — E6013 for shop welding",
    source="Website",
    notes="Also +91 98814 98241",
)
add(
    name="Lear Corporation",
    aka="",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Auto-component manufacturers",
    size="Large",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW;GMAW",
    electrodes="E6013;E7018",
    volume="Med",
    pitch="Auto seating OEM — fixtures/maintenance welding electrodes",
    source="Chamber directory (GCCIA)",
    notes="Large MNC; expect formal vendor process",
)
add(
    name="Festo India Pvt Ltd",
    aka="Festo",
    address="Bhosari MIDC, Pune - 411026",
    block="Bhosari MIDC",
    industry="Auto-component manufacturers",
    size="Large",
    phone="",
    phone_alt="",
    email="",
    website="",
    contact="",
    role="Purchase",
    conf="Low",
    year="",
    employees="",
    processes="SMAW",
    electrodes="E6013",
    volume="Low",
    pitch="Automation MNC — plant maintenance electrode kit only",
    source="Chamber directory (GCCIA)",
    notes="Low SMAW; maintenance angle",
)

# Real companies from websites / TradeIndia / directories (with plot where known)
EXTRA = [
    (
        "Vishal Fabricators & Engineering Works",
        "Sheet-metal fabrication",
        "SME",
        "Plot No. 105, Sector-10, PCNTDA MIDC, Bhosari, Pune - 411026",
        "Sector 10",
        "Sheet/CNC fab — E6013 primary",
        "+91",
        "",
        "",
        "https://www.tradeindia.com/vishal-fabricators-engineering-works-25217955/",
        "",
        "TradeIndia",
        "GST 27ARJPK3872C1ZR; est. 2016",
    ),
    (
        "Nihal Industries",
        "Auto-component manufacturers",
        "SME",
        "Plot No. 260, Sector-10, PCNTDA, Bhosari, Pune - 411026",
        "Sector 10",
        "Auto sheet tools/fixtures — E6013 for fixture fab + maintenance",
        "+91 99220 10786",
        "+91 90903 67171",
        "jabbar.shaikh@nihalind.com",
        "https://www.nihalind.com",
        "Jabbar Shaikh",
        "Website",
        "Unit-2: Plot 161, J Block MIDC Bhosari; sister Maxrich Industries",
    ),
    (
        "Maxrich Industries",
        "Machine shops",
        "SME",
        "Bhosari MIDC (Nihal group), Pune - 411026",
        "Bhosari MIDC",
        "Precision machining — repair/fixture E6013",
        "+91 99220 10786",
        "",
        "jabbar.shaikh@nihalind.com",
        "https://www.nihalind.com",
        "",
        "Website",
        "Part of Nihal group; Hardford VMC shop",
    ),
    (
        "Supertech Engineers & Fabricators",
        "Crane manufacturers",
        "SME",
        "Plot 80, Sector-10, MIDC Bhosari, Pune - 411026",
        "Sector 10",
        "EOT cranes & MH trolleys — E7018 girder welding",
        "",
        "",
        "",
        "https://www.tradeindia.com/supertech-engineers-fabricators-2284267/",
        "Mr. Sachin Pujari",
        "TradeIndia",
        "GST 27AMWPP1987H1Z5; also listed J Block addresses in directories",
    ),
    (
        "Super-Tech Fabrication",
        "Heavy fabrication",
        "Large",
        "J-251/252, MIDC Bhosari (behind Tata Motors), Pune - 411026; also Chakan MIDC unit",
        "J Block",
        "HRSG casings, chimneys, ducts, tanks, hoppers, platforms — high E7018 volume",
        "+91 20 27472213",
        "+91 20 27441102",
        "supertech@vsnl.net",
        "https://supertechfabrication.com",
        "N. P. Khodade / L. N. Khodade",
        "Website;Directory",
        "Est. 1990; ISO 9001; Bhosari + Chakan plants; boiler components & structural steel; also +91 20 25663290",
    ),
    (
        "Ghanokar Technology",
        "Gate/grill manufacturers",
        "Micro",
        "No. 1, Indrayani Nagar, Sector 2, Bhosari, Pune - 411026",
        "Sector 2",
        "Gates & fencing — E6013",
        "",
        "",
        "",
        "https://www.tradeindia.com/",
        "",
        "TradeIndia",
        "Near Bhosari industrial belt",
    ),
    (
        "Amruta Engineering Works",
        "Gate/grill manufacturers",
        "Micro",
        "S. No. 229, Pune Nashik Highway, Near Khandoba Temple, Bhosari",
        "Bhosari highway",
        "Designer gates — E6013",
        "",
        "",
        "",
        "",
        "Rajendar Biradar",
        "IndianYellowPages",
        "Adjacent to Bhosari industrial catchment",
    ),
]

# Legacy Pune MIDC / Bhosari directory rows: name, industry, size, address, block, phone, pitch
DIRECTORY_ROWS = [
    ("S & S Tooling", "Machine shops", "Micro", "Plot No. W-18, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27124792", "Tooling shop — E6013 repair/fixture welding"),
    ("Saher Enterprises", "General engineering", "Micro", "Plot No. 139, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27124783", "Engineering unit — E6013 entry"),
    ("Sachin Industries", "General engineering", "SME", "Plot No. S-68, MIDC, Bhosari, Pune - 411026", "S Block", "020-27126446", "MIDC unit — verify fab, pitch E6013"),
    ("Sachin Enterprises (S-31)", "General engineering", "Micro", "Plot No. S-31, MIDC, Bhosari, Pune - 411026", "S Block", "020-27121660", "Workshop — E6013 small packs"),
    ("Sahayog Founders & Engineers", "Foundries", "SME", "Plot No. T/S-37, General Block, MIDC, Bhosari, Pune - 411026", "General Block", "020-66111662", "Foundry/eng — Mn hardfacing + repair rods"),
    ("Sahil Fabricators", "Steel fabrication", "Micro", "Sector No. 7, Plot No. 284, PCNTDA Industrial Estate, Bhosari, Pune - 411026", "Sector 7", "9921278758", "Fabricator — E6013/E7018"),
    ("SAA Industries", "General engineering", "SME", "Plot No. 133, Sector No. 10, PCNTDA, Bhosari, Pune - 411026", "Sector 10", "020-66307016", "Sector 10 unit — E6013"),
    ("Sadguru Equipments Pvt Ltd", "Machine/equipment manufacturers", "SME", "Plot No. 88, Sector No. 7, PCNTDA, Bhosari, Pune - 411026", "Sector 7", "020-27121341", "Equipment OEM — E7018 frames"),
    ("Saesh Industries", "General engineering", "SME", "Plot No. 293, T Block, MIDC, Bhosari, Pune - 411026", "T Block", "020-27121327", "T Block eng unit — E6013"),
    ("Sagar Machine Tools", "Machine shops", "SME", "Plot No. 140, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27128415", "Machine tools — fixture welding E6013"),
    ("Sahas Auto Components", "Auto-component manufacturers", "SME", "Plot No. J-58, S Block, MIDC, Bhosari, Pune - 411026", "J/S Block", "9823462300", "Auto components — maintenance electrodes"),
    ("Sai Auto Stampings", "Auto-component manufacturers", "SME", "Sector No. 7, Plot No. 126, PCNTDA, MIDC, Bhosari, Pune - 411026", "Sector 7", "020-27124711", "Stampings — fixture/repair E6013"),
    ("Sai Engineering (Sector 10)", "General engineering", "Micro", "Plot No. 131, Sector No. 10, PCNTDA, Bhosari, Pune - 411026", "Sector 10", "9881204323", "Engineering shop — E6013"),
    ("Sai Engineers (W-57)", "General engineering", "Micro", "Plot No. W-57, S Block, Gala No. 6, MIDC, Bhosari, Pune - 411026", "S Block", "020-56306265", "Workshop — E6013"),
    ("Sai Industries (W-225)", "General engineering", "SME", "Plot No. W-225, MIDC, Bhosari, Pune - 411026", "W/S Block", "9922901390", "Industrial unit — verify weld use"),
    ("Sai Industries (J-444)", "General engineering", "SME", "Plot No. J-444, MIDC, Bhosari, Pune - 411026", "J Block", "020-66302800", "J Block unit — E6013/E7018"),
    ("Sai Industries (112/8 S Block)", "General engineering", "SME", "112/8, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27120558", "S Block unit — E6013"),
    ("Salaskar Automotive Pvt Ltd", "Auto-component manufacturers", "SME", "Plot No. 245, Sector No. 7, PCNTDA, MIDC, Bhosari, Pune - 411026", "Sector 7", "020-65322379", "Auto — fixture welding electrodes"),
    ("Salunkhe Crane Service", "Industrial maintenance", "Micro", "Plot No. 20/2/4, J Block, Opp. Kwality Ice Cream, MIDC, Bhosari, Pune - 411026", "J Block", "020-27130745", "Crane service — cutting + E6013 maintenance"),
    ("Sam Hitech Components Pvt Ltd", "Auto-component manufacturers", "SME", "Plot No. J-83, MIDC, Bhosari, Pune - 411026", "J Block", "020-66111675", "Auto components — shop electrodes"),
    ("Samarth Engineers (J-415)", "General engineering", "SME", "Plot No. J-415, MIDC, Bhosari, Pune - 411026", "J Block", "020-27129928", "Engineering — E6013/E7018"),
    ("Samarth Engineers (Sector 10-74)", "General engineering", "SME", "Plot No. 74, Sector No. 10, PCNTDA, Bhosari, Pune - 411026", "Sector 10", "020-66126062", "Sector 10 eng — E6013"),
    ("Samarth Engineers (Sector 10-4/18)", "Machine shops", "Micro", "Plot No. 4/18, Sector No. 10, PCNTDA, Bhosari, Pune - 411026", "Sector 10", "020-66146033", "Machine shop — E6013"),
    ("Sampradeep Engineering Company", "General engineering", "SME", "Plot No. 283, Sector No. 7, Electronic Zone, Bhosari, Pune - 411026", "Sector 7", "020-66305011", "Engineering — E6013"),
    ("Sandeep Engineering Works (directory)", "Foundries", "SME", "Plot No. 169, Sector No. 10, PCNTDA, MIDC, Bhosari, Pune - 411026", "Sector 10", "020-64101431", "Casting/eng works — hardfacing + E6013"),
    ("Sandeep Steels", "Steel fabrication", "SME", "Plot No. 71/B/52, General Block, Kheera Industrial Premises, Bhosari, Pune - 411026", "General Block", "020-27122438", "Steel works — E6013/E7018"),
    ("Sanjay Enterprises (W-208)", "General engineering", "Micro", "Plot No. W-208, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-66115069", "Workshop — E6013"),
    ("Sanjay Enterprises (W-160/A)", "General engineering", "Micro", "Plot No. W-160/A, S Block MIDC, Bhosari, Pune - 411026", "S Block", "020-46768836", "Workshop — E6013"),
    ("Sankalp Enterprises (S-206)", "General engineering", "SME", "S-206, MIDC, Bhosari, Pune - 411026", "S Block", "020-27120156", "MIDC unit — E6013"),
    ("Sankalp Technologies", "Machine/equipment manufacturers", "SME", "Plot No. 242, Sector No. 7, PCNTDA, Bhosari, Pune - 411026", "Sector 7", "020-66125494", "Tech/equipment — E6013/E7018"),
    ("Sankalpana Industries", "General engineering", "SME", "Plot No. 54, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27129828", "Industrial unit — E6013"),
    ("Sanmati Pressings Pvt Ltd", "Auto-component manufacturers", "SME", "Plot No. J-9, MIDC, Bhosari, Pune - 411026", "J Block", "020-66111379", "Pressings — fixture electrodes"),
    ("Sarath Engineering", "General engineering", "SME", "Plot No. 126, Sector No. 10, PCNTDA, Near Times of India, Bhosari, Pune - 411026", "Sector 10", "020-64100409", "Engineering — E6013"),
    ("Saraswali Enterprises", "General engineering", "SME", "Plot No. S-113/7, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27122456", "S Block unit — E6013"),
    ("Sathe And Sathe", "General engineering", "SME", "Plot No. 61, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27120391", "Engineering firm — verify weld demand"),
    ("Satyam Industries (S-112/7/2)", "General engineering", "SME", "Plot No. S-112/7/2, MIDC, Bhosari, Pune - 411026", "S Block", "020-27126297", "Industrial unit — E6013"),
    ("Satyam Industries (Sector 7-286)", "General engineering", "SME", "Plot No. 286, Sector No. 7, PCNTDA, Bhosari, Pune - 411026", "Sector 7", "9881204322", "Sector 7 unit — E6013"),
    ("Saurabh Mechanical Maintenance Works", "Industrial maintenance", "Micro", "Plot No. 225, Sector No. 7, PCNTDA, MIDC, Bhosari, Pune - 411026", "Sector 7", "020-32547976", "Maintenance — E6013 + cutting + Mn"),
    ("Savan Ancillaries", "Auto-component manufacturers", "SME", "Plot No. J-447, MIDC, Bhosari, Pune - 411026", "J Block", "020-32314327", "Ancillaries — shop electrodes"),
    ("Sawalka Tools & Machines Pvt Ltd", "Machine/equipment manufacturers", "SME", "Plot No. J-196, MIDC, Bhosari, Pune - 411026", "J Block", "020-66114422", "Tools/machines — E6013/E7018"),
    ("Sawant Engineers", "General engineering", "SME", "4/40, Sect No. 10, Near Times of India, PCNTDA, MIDC, Bhosari, Pune - 411026", "Sector 10", "020-66300302", "Engineering — E6013"),
    ("Sayali Enterprises", "General engineering", "Micro", "Plot No. J-486, Bhosari MIDC, Pune - 411026", "J Block", "020-27130457", "Workshop — E6013"),
    ("Saynak Hydraulics", "Machine/equipment manufacturers", "SME", "Plot No. 179, Sector 7, PCNTDA Industrial Estate, Bhosari, Pune - 411026", "Sector 7", "020-66306025", "Hydraulics equipment — structural E7018"),
    ("Saz Metals", "Steel fabrication", "SME", "Plot No. W-109, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27120152", "Metals/fab — E6013/E7018"),
    ("Scan Thermocon Inc", "Machine/equipment manufacturers", "SME", "Plot No. 180, Sector No. 7, PCNTDA, Near Times of India, MIDC, Bhosari, Pune - 411026", "Sector 7", "020-66302874", "Equipment — E6013"),
    ("Schmalz India Pvt Ltd", "Material-handling equipment", "Large", "Plot No. J-38, J Block, MIDC, Bhosari, Pune - 411026", "J Block", "020-40725500", "Vacuum MH OEM — maintenance electrodes"),
    ("Screwtech Engineering Pvt Ltd", "Machine shops", "SME", "Plot No. J-31/4, MIDC, J Block, Bhosari, Pune - 411026", "J Block", "020-27130877", "Precision eng — fixture E6013"),
    ("Serview Enterprises", "General engineering", "SME", "Plot No. S-184, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27120845", "Engineering — E6013"),
    ("Seva Engineering", "General engineering", "SME", "Plot No. 305/2, Sector No. 10, PCNTDA, Bhosari, Pune - 411026", "Sector 10", "020-24450363", "Engineering — E6013"),
    ("Shahade Fabricators", "Steel fabrication", "Micro", "Plot No. 226, Sector No. 10, Near Sai Associates, Bhosari, Pune - 411026", "Sector 10", "9422360934", "Fabricator — E6013/E7018 Hot lead"),
    ("Shailesh Industries", "General engineering", "SME", "Plot No. J-15, S-Block, Bhosari, Pune - 411026", "J/S Block", "020-27122365", "Industrial unit — E6013"),
    ("Shakti Industries (J-528)", "General engineering", "SME", "Plot No. J-528, MIDC, Bhosari, Pune - 411026", "J Block", "020-66114741", "Industrial unit — E6013"),
    ("Shan Engineering Company", "General engineering", "SME", "Sector No. 10, Plot No. 99, PCNTDA Industrial Zone, Bhosari, Pune - 411026", "Sector 10", "020-66302651", "Engineering — E6013"),
    ("Shape Engineers", "General engineering", "SME", "Sector 10, Plot No. 305, PCNTDA, Bhosari, Pune - 411026", "Sector 10", "9850827519", "Engineering — E6013"),
    ("Sharada Industries (W-199/B)", "General engineering", "SME", "Plot No. W-199/B, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27120962", "Industrial unit — E6013"),
    ("Sharex Chemicals Pvt Ltd", "Industrial maintenance", "SME", "Plot No. J-317, MIDC, Bhosari, Pune - 411026", "J Block", "020-27121826", "Plant maintenance electrodes"),
    ("Sharp Engineering", "General engineering", "SME", "Plot No. 81-B/3, General Block, Bhosari, Pune - 411026", "General Block", "020-27122613", "Engineering — E6013"),
    ("Sharptech Precision Pvt Ltd", "Machine shops", "SME", "Plot No. W-111, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27110733", "Precision — fixture welding"),
    ("Sheen Engineering Pvt Ltd", "General engineering", "SME", "Plot No. T-48, MIDC, Bhosari, Pune - 411026", "T Block", "020-27120995", "Engineering — E6013"),
    ("Sheetal Rubber Products Pvt Ltd", "Auto-component manufacturers", "SME", "Plot No. J-395, MIDC, Bhosari, Pune - 411026", "J Block", "020-27121388", "Rubber/auto — maintenance electrodes"),
    ("Shelimo Cores", "Foundries", "SME", "Plot No. T-72, MIDC, Bhosari, Pune - 411026", "T Block", "020-27128339", "Cores/foundry support — repair rods"),
    ("Shilpa Industries", "General engineering", "SME", "Plot No. W-248, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27122537", "Industrial unit — E6013"),
    ("Shimja Engineers & Contractors", "Structural fabrication", "SME", "Plot No. 323, J Block, MIDC, Bhosari, Pune - 411026", "J Block", "020-46768974", "Contract fab — E6013/E7018"),
    ("Shiraj Enterprises", "General engineering", "SME", "Plot No. 156, Sector No. 7, PCNTDA, Bhosari, Pune - 411026", "Sector 7", "020-27124845", "Engineering — E6013"),
    ("Shiv Engineering (S-33)", "General engineering", "SME", "Plot No. S-33, T Block, Bhosari, Pune - 411026", "T Block", "020-27127104", "Engineering — E6013"),
    ("Shiv Industrial Products", "Machine/equipment manufacturers", "SME", "Plot No. 339, J Block, MIDC, Bhosari, Pune - 411026", "J Block", "020-27122962", "Industrial products — E7018"),
    ("Shitole Engineering Pvt Ltd", "General engineering", "SME", "S Block, Plot No. 170, MIDC, Bhosari, Pune - 411026", "S Block", "020-27125444", "Engineering — E6013"),
    ("Shore Auto Rubber Exports Pvt Ltd", "Auto-component manufacturers", "Large", "Plot No. C-2/1, Technicians Block, Bhosari Industrial Estate, MIDC, Pune - 411026", "Technicians Block", "020-27127701", "Auto rubber OEM — maintenance electrodes"),
    ("Shraddha Engineers & Fabricators", "Steel fabrication", "SME", "Plot No. J-29, MIDC, Bhosari, Pune - 411026", "J Block", "020-27120386", "Fabricators — E6013/E7018 Hot"),
    ("Shradha Engineers", "General engineering", "SME", "Plot No. J-475, MIDC, Bhosari, Pune - 411026", "J Block", "020-27460257", "Engineering — E6013"),
    ("Shradha Engineering Works", "Machine shops", "Micro", "Plot No. 19, Sector No. 10, PCNTDA, Bhosari, Pune - 411026", "Sector 10", "985778862", "Job shop — E6013"),
    ("Shree Automation Pvt Ltd", "Machine/equipment manufacturers", "SME", "Plot No. J-201, MIDC, Bhosari, Pune - 411026", "J Block", "020-27441424", "Automation equipment — E6013/E7018"),
    ("Shree Balasai Industries", "General engineering", "SME", "Sector No. 7, Plot No. 33, PCNTDA Industrial Estate, Bhosari, Pune - 411026", "Sector 7", "020-27127688", "Industrial unit — E6013"),
    ("Shree Engineering (112/5 S Block)", "Steel fabrication", "SME", "Plot No. 112/5, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27127711", "Steel eng/fab — E6013/E7018"),
    ("Shree Fabricators (S-4/2)", "Steel fabrication", "SME", "Plot No. S-4/2, T Block, MIDC, Bhosari, Pune - 411026", "T Block", "020-27120150", "Fabricators — E6013/E7018 Hot"),
    ("Shree Gajanan Engineering Works (Sector 7)", "General engineering", "SME", "Plot No. 252, Sector No. 7, PCNTDA, Bhosari, Pune - 411026", "Sector 7", "020-66302920", "Engineering works — E6013"),
    ("Shree Ganesh Engineering Works (S Block Plot 5)", "General engineering", "SME", "S Block, Plot No. 5, MIDC, Bhosari, Pune - 411026", "S Block", "020-27122492", "Engineering works — E6013"),
    ("Shree Ganesh Engineering Company (Sector 10)", "General engineering", "SME", "Sector No. 10, Plot No. 111, PCNTDA, Bhosari, Pune - 411026", "Sector 10", "9673004415", "Engineering — E6013"),
    ("Shree Ganesh Pressing And Fabricators", "Sheet-metal fabrication", "SME", "Plot No. W-111, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-26767964", "Pressing & fab — E6013"),
    ("Shree Govind Steels", "Steel fabrication", "SME", "W-12, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27111634", "Steels — E6013/E7018"),
    ("Shree Laxmi Fabrication", "Steel fabrication", "Micro", "T-71/1A/8, General Block, Near Jayanand Khira Co., Bhosari, Pune - 411026", "General Block", "9822055447", "Fabrication — E6013 Hot mobile"),
    ("Shree Mahaveer Industries", "General engineering", "SME", "Plot No. J-408, MIDC, Bhosari, Pune - 411026", "J Block", "020-27122558", "Industrial unit — E6013"),
    ("Shree Parshwa Industries", "General engineering", "SME", "Plot No. 139, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27122604", "Industrial unit — E6013"),
    ("Shree Precision", "Machine shops", "SME", "Plot No. 329, J Block, MIDC Bhosari, Pune - 411026", "J Block", "020-27122645", "Precision shop — E6013"),
    ("Shree Pressing (Sector 7-241)", "Auto-component manufacturers", "SME", "Plot No. 241, Sector No. 7, MIDC, PCNTDA, Bhosari, Pune - 411026", "Sector 7", "9604310080", "Pressings — fixture electrodes"),
    ("Shree Ramdev Industries", "General engineering", "SME", "Plot No. 194, S Block, MIDC, Bhosari, Pune - 411026", "S Block", "020-27122921", "Industrial unit — E6013"),
    ("Shree Samarth Industries (Sector 7-237)", "General engineering", "SME", "Plot No. 237, Sector No. 7, PCNTDA, Bhosari, Pune - 411026", "Sector 7", "9881204321", "Industrial unit — E6013"),
    ("Shree Stamping", "Auto-component manufacturers", "SME", "Plot No. J-158, MIDC, Bhosari, Pune - 411026", "J Block", "020-27120378", "Stampings — E6013 fixtures"),
    ("Shree Yash Auto Comp Pvt Ltd", "Auto-component manufacturers", "SME", "Plot No. J-363, MIDC, Bhosari, Pune - 411026", "J Block", "020-27120955", "Auto components — maintenance electrodes"),
    ("Sharp Arc Welding Services", "Industrial maintenance", "Micro", "Paras Industrial Premises, Gala No. 10, Plot No. 71/1B/12, General T Block, MIDC, Bhosari, Pune - 411026", "General Block", "9822073369", "Welding services — stock Bharatweld electrodes"),
]

PROCESS_BY_INDUSTRY = {
    "Heavy fabrication": ("SMAW;GMAW;Cutting", "E6013;E7018;Cutting", "High"),
    "Steel fabrication": ("SMAW;GMAW", "E6013;E7018", "High"),
    "Structural fabrication": ("SMAW;GMAW", "E6013;E7018", "High"),
    "Boiler/tank manufacturers": ("SMAW;GTAW", "E7018;E6013;E308L", "High"),
    "Heavy engineering": ("SMAW;GMAW;Hardfacing", "E7018;E6013;Mn hardfacing", "High"),
    "Machine/equipment manufacturers": ("SMAW;GMAW;GTAW", "E7018;E6013;E308L", "Med"),
    "Industrial maintenance": ("SMAW;Cutting;Hardfacing", "E6013;E7018;Cutting;Mn hardfacing", "Med"),
    "Sheet-metal fabrication": ("SMAW;GMAW", "E6013", "Med"),
    "Auto-component manufacturers": ("SMAW;GMAW", "E6013;E7018", "Med"),
    "Agricultural equipment": ("SMAW;GMAW;Hardfacing", "E6013;E7018;Mn hardfacing", "Med"),
    "Material-handling equipment": ("SMAW;GMAW", "E6013;E7018", "Med"),
    "Crane manufacturers": ("SMAW;GMAW", "E7018;E6013", "High"),
    "Trailer/body builders": ("SMAW;GMAW", "E6013;E7018", "High"),
    "Foundries": ("SMAW;Hardfacing;Cutting", "E6013;Mn hardfacing;Cutting", "Low"),
    "General engineering": ("SMAW", "E6013;E7018", "Low"),
    "Machine shops": ("SMAW", "E6013", "Low"),
    "Small workshops": ("SMAW", "E6013", "Low"),
    "Metal furniture": ("SMAW", "E6013", "Low"),
    "Gate/grill manufacturers": ("SMAW", "E6013", "Low"),
}

PRODUCTS_BY_INDUSTRY = {
    "Heavy fabrication": "Heavy steel fabrication; structural & pressure parts; welded assemblies",
    "Steel fabrication": "Steel structures; frames; general metal fabrication",
    "Structural fabrication": "Beams, columns, platforms, structural steelwork",
    "Heavy engineering": "Heavy machinery components; engineered welded fabrications",
    "Boiler/tank manufacturers": "Boilers; pressure vessels; tanks; heat exchangers",
    "Machine/equipment manufacturers": "Industrial machines/equipment frames & fabricated parts",
    "Industrial maintenance": "Plant repair welding; maintenance fabrication; cutting/hardfacing jobs",
    "Sheet-metal fabrication": "Sheet-metal components; enclosures; canopies; light fab",
    "Auto-component manufacturers": "Auto stampings/assemblies; fixtures; shop welding",
    "Agricultural equipment": "Agri implements; trailers; equipment frames",
    "Material-handling equipment": "Conveyors; trolleys; stackers; MH structures",
    "Crane manufacturers": "EOT/jib cranes; girders; hoists; crane structures",
    "Trailer/body builders": "Trailer chassis; truck/container bodies",
    "Foundries": "Castings; foundry repair & hardfacing",
    "General engineering": "General engineering job work; light fabrication",
    "Machine shops": "Machining + fixture/repair welding",
    "Small workshops": "Workshop fabrication & repair",
    "Metal furniture": "Metal furniture frames",
    "Gate/grill manufacturers": "Gates; grills; fencing fabrication",
}

TIER_BY_INDUSTRY = {
    "Heavy fabrication": 1,
    "Steel fabrication": 1,
    "Structural fabrication": 1,
    "Boiler/tank manufacturers": 1,
    "Heavy engineering": 1,
    "Machine/equipment manufacturers": 1,
    "Industrial maintenance": 1,
    "Sheet-metal fabrication": 1,
    "Auto-component manufacturers": 2,
    "Agricultural equipment": 2,
    "Material-handling equipment": 2,
    "Crane manufacturers": 2,
    "Trailer/body builders": 2,
    "Foundries": 2,
    "General engineering": 3,
    "Machine shops": 3,
    "Small workshops": 3,
    "Metal furniture": 3,
    "Gate/grill manufacturers": 3,
}

# Expand EXTRA (website / TradeIndia enriched)
for (
    name,
    industry,
    size,
    address,
    block,
    pitch,
    phone,
    phone_alt,
    email,
    website,
    contact,
    source,
    notes,
) in EXTRA:
    procs, elec, vol = PROCESS_BY_INDUSTRY[industry]
    phone_n = "" if phone.strip() in ("", "+91") else phone
    add(
        name=name,
        aka="",
        address=address,
        block=block,
        industry=industry,
        size=size,
        phone=phone_n,
        phone_alt=phone_alt,
        email=email,
        website=website,
        contact=contact,
        role="Owner" if contact else ("Owner" if size == "Micro" else "Purchase"),
        conf="Med" if contact or phone_n else "Low",
        year="",
        employees="",
        processes=procs,
        electrodes=elec,
        volume=vol,
        pitch=pitch,
        source=source,
        notes=notes + " | Directory/web phones may be stale — re-verify before dialing",
    )

# Expand DIRECTORY_ROWS (legacy Pune MIDC / Bhosari public directory)
for name, industry, size, address, block, phone, pitch in DIRECTORY_ROWS:
    procs, elec, vol = PROCESS_BY_INDUSTRY[industry]
    phone_fmt = phone
    if phone and not phone.startswith("+") and phone[0].isdigit():
        if phone.startswith("020"):
            phone_fmt = "+91 " + phone
        elif len(re.sub(r"\D", "", phone)) == 10:
            phone_fmt = "+91 " + phone
    add(
        name=name,
        aka="",
        address=address,
        block=block,
        industry=industry,
        size=size,
        phone=phone_fmt,
        phone_alt="",
        email="",
        website="",
        contact="",
        role="Owner" if size == "Micro" else "Purchase",
        conf="Low",
        year="",
        employees="",
        processes=procs,
        electrodes=elec,
        volume=vol,
        pitch=pitch,
        source="Pune MIDC / Bhosari public directory (stale risk)",
        notes="Phone from older public directory — confirm on Google Maps / call before WhatsApp campaign",
    )

# Enrich known plants with products / plant labels (applied onto RAW dicts)
PRODUCT_OVERRIDES = {
    "Super-Tech Fabrication": {
        "products": "HRSG casing panels; chimneys/stacks; ducts; tanks; hoppers; platforms & railings; structural steelwork; boiler components",
        "plant": "J-251/252 Bhosari plant (+ Chakan unit)",
    },
    "Silson Boilers": {
        "products": "IBR steam boilers; thermic fluid heaters; pressure vessels; heat exchangers",
        "plant": "115/2 General Block plant",
    },
    "Rakhoh Industries Pvt Ltd": {
        "products": "Steam boilers; industrial boilers; boiler pressure parts",
        "plant": "S-11 T Block plant",
    },
    "Fabri-Tek Engineers": {
        "products": "ASME pressure vessels; storage tanks; process equipment",
        "plant": "S-151 Bhosari (+ Chakan Unit-II)",
    },
    "Radiant Heat Exchanger Pvt Ltd": {
        "products": "Shell & tube heat exchangers; pressure vessels; process equipment",
        "plant": "S-116/2 & S-19 Bhosari plants",
    },
    "Advance Preci-Tech": {
        "products": "Heavy pressure vessel fabrication; precision engineering fab",
        "plant": "J-166 plant",
    },
    "Datsons Engineering Works Pvt Ltd": {
        "products": "Auto sheet-metal; canopies; fabricated auto components",
        "plant": "W-13/14/15 S Block (Unit-1)",
    },
    "Malgudi Cranes & Components": {
        "products": "EOT cranes; goliath cranes; crane components",
        "plant": "Sector 7 Plot 238",
    },
    "Malgudi Associates": {
        "products": "EOT & jib cranes; material-handling cranes",
        "plant": "Sector 7 Plot 149/2",
    },
}
for r in RAW:
    ov = PRODUCT_OVERRIDES.get(r["name"])
    if not ov:
        continue
    if ov.get("products") and not r.get("products"):
        r["products"] = ov["products"]
    if ov.get("plant") and not r.get("plant"):
        r["plant"] = ov["plant"]

# Parked (non-fit examples)
PARKED = [
    {
        "name": "Emcure Pharmaceuticals Ltd",
        "address": "Bhosari MIDC, Pune - 411026",
        "industry": "Pharma (parked)",
        "reason": "Not core welding electrode buyer; maintenance-only angle later",
        "source": "Chamber directory (GCCIA)",
    },
    {
        "name": "Kwality Paints",
        "address": "Bhosari MIDC, Pune - 411026",
        "industry": "Paints (parked)",
        "reason": "Non-metal manufacturing; exclude from Phase 1",
        "source": "Chamber directory (GCCIA)",
    },
]


def maps_url(name: str, address: str) -> str:
    q = re.sub(r"\s+", "+", f"{name} {address}")
    return f"https://www.google.com/maps/search/?api=1&query={q}"


def score_row(tier: int, phone: str, contact: str, volume: str, website: str, email: str) -> tuple[int, str]:
    s = {1: 3, 2: 2, 3: 1}.get(tier, 1)
    if phone.strip():
        s += 1
    if contact.strip():
        s += 1
    if volume == "High":
        s += 1
    # tiny boost if website or email when no phone (still capped)
    if not phone.strip() and (website.strip() or email.strip()):
        s += 0  # already requires contact channel elsewhere
    s = min(s, 5)
    if s >= 4:
        label = "Hot"
    elif s == 3:
        label = "Warm"
    else:
        label = "Later"
    return s, label


def verification_status(phone: str, website: str, email: str, source: str) -> str:
    if "UNVERIFIED" in (source or "") or "Maps pending" in (source or "") or "Geo seed" in (source or ""):
        return "Unverified"
    if phone.strip() and (website.strip() or email.strip() or "Website" in source):
        return "Phone-ok"
    if phone.strip() or website.strip() or email.strip():
        return "Unverified"
    return "Unverified"


def has_outreach_channel(r: dict) -> bool:
    return bool(r.get("phone") or r.get("website") or r.get("email"))


def build_rows() -> tuple[list[dict], list[dict], list[dict]]:
    seen = set()
    all_rows: list[dict] = []
    for i, r in enumerate(RAW, start=1):
        key = r["name"].strip().lower()
        if key in seen:
            continue
        seen.add(key)
        industry = r["industry"]
        tier = TIER_BY_INDUSTRY.get(industry, 3)
        sc, label = score_row(
            tier,
            r.get("phone", ""),
            r.get("contact", ""),
            r.get("volume", "Low"),
            r.get("website", ""),
            r.get("email", ""),
        )
        whatsapp = ""
        phone = r.get("phone", "")
        if phone and re.search(r"9\d{9}", phone.replace(" ", "").replace("-", "")):
            m = re.search(r"(9\d{9})", phone.replace(" ", "").replace("-", ""))
            if m:
                whatsapp = "+91 " + m.group(1)
        row = {
            "company_id": f"BHO-{i:03d}",
            "company_name": r["name"],
            "also_known_as": r.get("aka", ""),
            "plot_address": r["address"],
            "area_block": r.get("block", ""),
            "pincode": "411026",
            "geo_lat": "",
            "geo_lng": "",
            "google_maps_url": maps_url(r["name"], r["address"]),
            "industry_category": industry,
            "tier": tier,
            "company_size_signal": r.get("size", ""),
            "phone_primary": phone,
            "phone_alt": r.get("phone_alt", ""),
            "whatsapp": whatsapp,
            "email": r.get("email", ""),
            "website": r.get("website", ""),
            "contact_person_name": r.get("contact", ""),
            "contact_person_role": r.get("role", ""),
            "decision_maker_confidence": r.get("conf", "Low"),
            "gstin": r.get("gstin", ""),
            "cin": r.get("cin", ""),
            "company_status": "",
            "directors": r.get("directors", ""),
            "year_established": r.get("year", ""),
            "employee_estimate": r.get("employees", ""),
            "plant_name": r.get("plant", "") or r.get("block", ""),
            "products_services": r.get("products", "")
            or PRODUCTS_BY_INDUSTRY.get(industry, "")
            or r.get("notes", ""),
            "processes_likely": r.get("processes", ""),
            "electrode_likely": r.get("electrodes", ""),
            "volume_signal": r.get("volume", ""),
            "current_supplier_known": "Unknown",
            "pitch_angle": r.get("pitch", ""),
            "priority_score": sc,
            "priority_label": label,
            "data_source": r.get("source", ""),
            "last_verified_date": TODAY if has_outreach_channel(r) and "Website" in r.get("source", "") else "",
            "verification_status": verification_status(
                phone, r.get("website", ""), r.get("email", ""), r.get("source", "")
            ),
            "outreach_status": "Not contacted",
            "notes": r.get("notes", ""),
            "assigned_to": "",
            "_has_channel": has_outreach_channel(r),
        }
        all_rows.append(row)

    # Prefer rows with outreach channel, then score, then tier
    ranked = sorted(
        all_rows,
        key=lambda x: (
            0 if x["_has_channel"] else 1,
            -x["priority_score"],
            x["tier"],
            x["company_name"],
        ),
    )

    prospects = []
    deferred = []
    for row in ranked:
        clean = {k: v for k, v in row.items() if not k.startswith("_")}
        if len(prospects) < 100:
            # renumber after freeze
            prospects.append(clean)
        else:
            deferred.append(clean)

    for idx, row in enumerate(prospects, start=1):
        row["company_id"] = f"BHO-{idx:03d}"
    for idx, row in enumerate(deferred, start=1):
        row["company_id"] = f"BHO-D{idx:03d}"

    parked_rows = []
    for idx, p in enumerate(PARKED, start=1):
        parked_rows.append(
            {
                "company_id": f"BHO-P{idx:03d}",
                "company_name": p["name"],
                "plot_address": p["address"],
                "pincode": "411026",
                "industry_category": p["industry"],
                "parked_reason": p["reason"],
                "data_source": p["source"],
                "outreach_status": "Parked",
                "notes": "Do not include in Phase 1 Hot dial list",
            }
        )
    return prospects, deferred, parked_rows


PROSPECT_FIELDS = [
    "company_id",
    "company_name",
    "also_known_as",
    "plant_name",
    "plot_address",
    "area_block",
    "pincode",
    "geo_lat",
    "geo_lng",
    "google_maps_url",
    "industry_category",
    "products_services",
    "tier",
    "company_size_signal",
    "phone_primary",
    "phone_alt",
    "whatsapp",
    "email",
    "website",
    "contact_person_name",
    "contact_person_role",
    "decision_maker_confidence",
    "gstin",
    "cin",
    "company_status",
    "directors",
    "year_established",
    "employee_estimate",
    "processes_likely",
    "electrode_likely",
    "volume_signal",
    "current_supplier_known",
    "pitch_angle",
    "priority_score",
    "priority_label",
    "data_source",
    "last_verified_date",
    "verification_status",
    "outreach_status",
    "notes",
    "assigned_to",
]


def write_csv(path: Path, rows: list[dict], fields: list[str]):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        for row in rows:
            w.writerow({k: row.get(k, "") for k in fields})


def main():
    prospects, deferred, parked = build_rows()
    write_csv(DATA / "bhosari-midc-prospects.csv", prospects, PROSPECT_FIELDS)
    write_csv(DATA / "bhosari-midc-deferred.csv", deferred, PROSPECT_FIELDS)
    write_csv(
        DATA / "bhosari-midc-parked.csv",
        parked,
        [
            "company_id",
            "company_name",
            "plot_address",
            "pincode",
            "industry_category",
            "parked_reason",
            "data_source",
            "outreach_status",
            "notes",
        ],
    )
    hot = [r for r in prospects if r["priority_label"] == "Hot"]
    write_csv(DATA / "bhosari-midc-hot-list.csv", hot, PROSPECT_FIELDS)

    # Outreach log template (empty)
    log_fields = [
        "log_id",
        "company_id",
        "company_name",
        "contact_date",
        "channel",
        "outcome",
        "next_followup",
        "sample_sent",
        "notes",
        "logged_by",
    ]
    write_csv(DATA / "bhosari-midc-outreach-log.csv", [], log_fields)

    tier_counts = {1: 0, 2: 0, 3: 0}
    for r in prospects:
        tier_counts[r["tier"]] += 1
    print(f"Raw unique: {len(prospects) + len(deferred)}")
    print(f"Prospects frozen: {len(prospects)}")
    print(f"Deferred: {len(deferred)}")
    print(f"Hot: {len(hot)}")
    print(f"Tier mix T1/T2/T3: {tier_counts[1]}/{tier_counts[2]}/{tier_counts[3]}")
    print(f"With phone: {sum(1 for r in prospects if r['phone_primary'])}")
    print(f"With website or email: {sum(1 for r in prospects if r['website'] or r['email'])}")


if __name__ == "__main__":
    main()
